// Generated by CoffeeScript 2.4.1
var messages, playMode;

playMode = 0; // 0=no play 1=play

messages = [];

//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiZGF0YS5qcyIsInNvdXJjZVJvb3QiOiIuLiIsInNvdXJjZXMiOlsiY29mZmVlXFxkYXRhLmNvZmZlZSJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiO0FBQUEsSUFBQSxRQUFBLEVBQUE7O0FBQUEsUUFBQSxHQUFXLEVBQVg7O0FBRUEsUUFBQSxHQUFXIiwic291cmNlc0NvbnRlbnQiOlsicGxheU1vZGUgPSAwICMgMD1ubyBwbGF5IDE9cGxheVxyXG5cclxubWVzc2FnZXMgPSBbXSJdfQ==
//# sourceURL=c:\github\2021\013-gpsKarta2\coffee\data.coffee