// Generated by CoffeeScript 2.4.1
var gpsPoints, messages, playMode;

playMode = 0; // 0=no play 1=play

messages = [];

gpsPoints = [];

//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiZGF0YS5qcyIsInNvdXJjZVJvb3QiOiIuLiIsInNvdXJjZXMiOlsiY29mZmVlXFxkYXRhLmNvZmZlZSJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiO0FBQUEsSUFBQSxTQUFBLEVBQUEsUUFBQSxFQUFBOztBQUFBLFFBQUEsR0FBVyxFQUFYOztBQUVBLFFBQUEsR0FBVzs7QUFFWCxTQUFBLEdBQVkiLCJzb3VyY2VzQ29udGVudCI6WyJwbGF5TW9kZSA9IDAgIyAwPW5vIHBsYXkgMT1wbGF5XHJcblxyXG5tZXNzYWdlcyA9IFtdXHJcblxyXG5ncHNQb2ludHMgPSBbXSJdfQ==
//# sourceURL=c:\github\2021\013-gpsKarta2\coffee\data.coffee