// Generated by CoffeeScript 2.4.1
var H, W, gpsPoints, messages, playMode;

W = window.innerWidth;

H = window.innerHeight;

playMode = 0; // 0=no play 1=play

messages = [];

gpsPoints = [];

//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiZGF0YS5qcyIsInNvdXJjZVJvb3QiOiIuLiIsInNvdXJjZXMiOlsiY29mZmVlXFxkYXRhLmNvZmZlZSJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiO0FBQUEsSUFBQSxDQUFBLEVBQUEsQ0FBQSxFQUFBLFNBQUEsRUFBQSxRQUFBLEVBQUE7O0FBQUEsQ0FBQSxHQUFJLE1BQU0sQ0FBQzs7QUFDWCxDQUFBLEdBQUksTUFBTSxDQUFDOztBQUVYLFFBQUEsR0FBVyxFQUhYOztBQUtBLFFBQUEsR0FBVzs7QUFFWCxTQUFBLEdBQVkiLCJzb3VyY2VzQ29udGVudCI6WyJXID0gd2luZG93LmlubmVyV2lkdGhcclxuSCA9IHdpbmRvdy5pbm5lckhlaWdodFxyXG5cclxucGxheU1vZGUgPSAwICMgMD1ubyBwbGF5IDE9cGxheVxyXG5cclxubWVzc2FnZXMgPSBbXVxyXG5cclxuZ3BzUG9pbnRzID0gW10iXX0=
//# sourceURL=c:\github\2021\013-gpsKarta2\coffee\data.coffee